/*
 * GPIO_cfg.h
 *
 *  Created on: Nov 12, 2023
 *      Author: Lenovo
 */

#ifndef GPIO_CFG_H_
#define GPIO_CFG_H_



#include "Std_Types.h"
#include "GPIO_prv.h"
 /*

OPTIONS FOR MODE :
-INPUT
-OUTPUT
-ALTFUN
-ANALOGUE
/////////////////////
OPTIONS FOR OUTPUT_TYPE :
-DONT_CARE
-PUSHPULL
-OPENDRAIN
///////////////////
OPTIONS FOR SPEED :
-LOWSPD
-MEDIUMSPD
-HIGHSPD
-VHIGHSPD
///////////////
OPTIONS FOR PUDR :
-DONT_CARE
-FLOATING
-PULLUP
-PULLDOWN


 */

/*                 PORTx_PINx_CFG(PORT,PIN ,MODE,TYPE,PUDR,SPEED)                                  */


/////////////////////////////////GPIO A
#define PORTA_PIN0_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_0 ,OUTPUT ,PUSHPULL,PULLDOWN ,HIGHSPD )
#define PORTA_PIN1_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_1 ,OUTPUT,PUSHPULL ,FLOATING ,HIGHSPD)
#define PORTA_PIN2_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_2 ,OUTPUT,PUSHPULL ,FLOATING ,HIGHSPD  )
#define PORTA_PIN3_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_3 ,OUTPUT,PUSHPULL,FLOATING,HIGHSPD)
#define PORTA_PIN4_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_4 ,OUTPUT,PUSHPULL,FLOATING ,HIGHSPD   )
#define PORTA_PIN5_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_5 ,OUTPUT,PUSHPULL,FLOATING ,HIGHSPD   )
#define PORTA_PIN6_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_6 ,OUTPUT,PUSHPULL,FLOATING ,HIGHSPD   )
#define PORTA_PIN7_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_7 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN8_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_8 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN9_CFG              PORTx_PINx_CFG(GPIO_A,GPIOPIN_9 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN10_CFG             PORTx_PINx_CFG(GPIO_A,GPIOPIN_10,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN11_CFG             PORTx_PINx_CFG(GPIO_A,GPIOPIN_11,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN12_CFG             PORTx_PINx_CFG(GPIO_A,GPIOPIN_12,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN13_CFG             PORTx_PINx_CFG(GPIO_A,GPIOPIN_13,ALTFUN  ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN14_CFG             PORTx_PINx_CFG(GPIO_A,GPIOPIN_14,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTA_PIN15_CFG             PORTx_PINx_CFG(GPIO_A,GPIOPIN_15,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )




////////////////////////////////// GPIO B


#define PORTB_PIN0_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_0 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN1_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_1 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN2_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_2 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN3_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_3 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN4_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_4 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN5_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_5 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN6_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_6 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN7_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_7 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN8_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_8 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN9_CFG              PORTx_PINx_CFG(GPIO_B,GPIOPIN_9 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN10_CFG             PORTx_PINx_CFG(GPIO_B,GPIOPIN_10,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN11_CFG             PORTx_PINx_CFG(GPIO_B,GPIOPIN_11,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN12_CFG             PORTx_PINx_CFG(GPIO_B,GPIOPIN_12,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN13_CFG             PORTx_PINx_CFG(GPIO_B,GPIOPIN_13,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN14_CFG             PORTx_PINx_CFG(GPIO_B,GPIOPIN_14,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTB_PIN15_CFG             PORTx_PINx_CFG(GPIO_B,GPIOPIN_15,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )






///////////////////////////////// GPIO C


#define PORTC_PIN0_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_0 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN1_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_1 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN2_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_2 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN3_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_3 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN4_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_4 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN5_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_5 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN6_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_6 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN7_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_7 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN8_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_8 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN9_CFG              PORTx_PINx_CFG(GPIO_C,GPIOPIN_9 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN10_CFG             PORTx_PINx_CFG(GPIO_C,GPIOPIN_10,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN11_CFG             PORTx_PINx_CFG(GPIO_C,GPIOPIN_11,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN12_CFG             PORTx_PINx_CFG(GPIO_C,GPIOPIN_12,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN13_CFG             PORTx_PINx_CFG(GPIO_C,GPIOPIN_13,OUTPUT  ,PUSHPULL  ,FLOATING ,HIGHSPD   )
#define PORTC_PIN14_CFG             PORTx_PINx_CFG(GPIO_C,GPIOPIN_14,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTC_PIN15_CFG             PORTx_PINx_CFG(GPIO_C,GPIOPIN_15,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )








///////////////////////////////// GPIO D


#define PORTD_PIN0_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_0 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN1_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_1 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN2_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_2 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN3_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_3 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN4_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_4 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN5_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_5 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN6_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_6 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN7_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_7 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN8_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_8 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN9_CFG              PORTx_PINx_CFG(GPIO_D,GPIOPIN_9 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN10_CFG             PORTx_PINx_CFG(GPIO_D,GPIOPIN_10,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN11_CFG             PORTx_PINx_CFG(GPIO_D,GPIOPIN_11,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN12_CFG             PORTx_PINx_CFG(GPIO_D,GPIOPIN_12,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN13_CFG             PORTx_PINx_CFG(GPIO_D,GPIOPIN_13,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN14_CFG             PORTx_PINx_CFG(GPIO_D,GPIOPIN_14,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTD_PIN15_CFG             PORTx_PINx_CFG(GPIO_D,GPIOPIN_15,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )




///////////////////////////////// GPIO E


#define PORTE_PIN0_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_0 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN1_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_1 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN2_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_2 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN3_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_3 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN4_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_4 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN5_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_5 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN6_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_6 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN7_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_7 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN8_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_8 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN9_CFG              PORTx_PINx_CFG(GPIO_E,GPIOPIN_9 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN10_CFG             PORTx_PINx_CFG(GPIO_E,GPIOPIN_10,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN11_CFG             PORTx_PINx_CFG(GPIO_E,GPIOPIN_11,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN12_CFG             PORTx_PINx_CFG(GPIO_E,GPIOPIN_12,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN13_CFG             PORTx_PINx_CFG(GPIO_E,GPIOPIN_13,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN14_CFG             PORTx_PINx_CFG(GPIO_E,GPIOPIN_14,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )
#define PORTE_PIN15_CFG             PORTx_PINx_CFG(GPIO_E,GPIOPIN_15,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD   )




///////////////////////////////// GPIO H


#define PORTH_PIN0_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_0 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN1_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_1 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN2_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_2 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN3_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_3 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN4_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_4 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN5_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_5 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN6_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_6 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN7_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_7 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN8_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_8 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN9_CFG              PORTx_PINx_CFG(GPIO_H,GPIOPIN_9 ,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN10_CFG             PORTx_PINx_CFG(GPIO_H,GPIOPIN_10,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN11_CFG             PORTx_PINx_CFG(GPIO_H,GPIOPIN_11,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN12_CFG             PORTx_PINx_CFG(GPIO_H,GPIOPIN_12,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN13_CFG             PORTx_PINx_CFG(GPIO_H,GPIOPIN_13,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN14_CFG             PORTx_PINx_CFG(GPIO_H,GPIOPIN_14,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )
#define PORTH_PIN15_CFG             PORTx_PINx_CFG(GPIO_H,GPIOPIN_15,INPUT   ,DONT_CARE ,PULLDOWN ,LOWSPD    )




#endif /* GPIO_CFG_H_ */
